### ISSUE TITLE
this filter drops all @metadata

### ISSUE THREAD

**Issue by jpcarey** [logstash-plugins/logstash-filter-clone#5] opened 2015-12-05 00:49 UTC

**Comment by wiibaa** [comment] 2015-12-05 06:53
Confirmed! The issue is in the logstash event#clone method. I reported this in logstash-core and will look for a workaround.

**Comment by driverpt** [comment] 2016-04-19 17:10
```
new_event = Logstash::Event.new(old_event.to_hash_with_metadata)
```

**Comment by jpcarey** [comment] 2016-04-27 17:36
@wiibaa @driverpt simple change, thoughts? https://github.com/jpcarey/logstash-filter-clone/commit/ff4590169fc8c7969b160099690fb246f18007ab

**Comment by jordansissel** [comment] 2016-04-27 18:00
I'm not sure if `to_hash_with_metadata` is a supported public API for the Event class.

**Comment by jordansissel** [comment] 2016-04-27 18:12
We'll need an event duplication/clone method that copies the metadata for fixing this.

**Comment by wiibaa** [comment] 2016-04-28 04:00
@jordansissel work on copying metadata + deep_clone is in progress in https://github.com/elastic/logstash/pull/4642

**Comment by uschtwill** [comment] 2017-03-30 16:39
Why is this issue closed? As far as I can tell, metadata is still deleted when cloning?!

**Comment by wiibaa** [comment] 2017-03-30 18:47
From the linked issues, it seems only fixed in the ruby implementation so LS 2.x and not in java event 5.x.
 @uschtwill thanks for reporting

**Comment by dmarkhas** [comment] 2017-09-17 16:04
Hi,

Any ETA on when this will get fixed?

**Comment by alkuzad** [comment] 2017-09-17 20:18
@dmarkhas go to upstream https://github.com/elastic/logstash/pull/4642 and ask @suyograo when it will be ported.

**Comment by dmarkhas** [comment] 2017-10-17 13:11
FYI this was fixed in https://github.com/elastic/logstash/pull/8385

**Closed** 2017-10-23 16:27 UTC
Labels: bug
